name: Check instructions

on: [push, pull_request]
  
jobs:
  setup-universal:
    runs-on: [ubuntu-slim,macos-latest,windows-11-arm]
    steps:
      - name: terminal verification
        run: echo hello

  setup-windows:
    runs-on: [windows-11-arm]
    steps:
      - name: git install
        run: | 
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.2/Git-2.56.0.2-64-bit.exe")
          start Git-2.56.0.2-64-bit.exe
      - name: Miniforge install
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe")
          start Miniforge3-Windows-x86_64.exe
          # That's all we can do for now folks
          # I have to figure out how to go through the installer from the cli...

  setup-unix:
    runs-on: [ubuntu-slim,macos-latest]
    steps:
      - name: git install
        run: |
          xcode-select --install
          git --version
      - name: Miniforge install
        run: | 
          cd Downloads
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash ~/Downloads/Miniforge3-$(uname)-$(uname -m).sh
          #Ugh, how do I get a new terminal again...?

  download-nsdf-data:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        include:
          - startdir: "%USERPROFILE%"
            ls: dir
            os: windows-11-arm
          - startdir: "~"
            ls: ls
            os: macos-latest
    steps:
      - name: download nsdf data
        run: |
          #ls for debug
          ls
          conda --version

          mkdir $startdir/Research
          cd $start/dirResearch
          git clone https://github.com/villano-lab/NSDF-Data.git
          cd $startdir/Research/NSDF-Data
          $ls

      - name: create conda env
        run: conda create -n darkmatter_cli_env -f requirements.txt
      - name: test env
        run: |
          conda activate darkmatter_cli_env
          cd $startdir/Research/NSDF-Data/python
          python -m pytest -q

          nsdf-cli version

          jupyter lab --version

      - name: set up j kernel
        run: python -m ipykernel install --user --name darkmatter_cli_env

      - name: permission
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "you@example.com"
          cd $startdir/Research/NSDF-Data
          git checkout -b student-yourname

